%YAML 1.2
---
name: Build Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'ros2'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'humble', container: 'osrf/ros:humble-desktop'}
    container: ${{ matrix.config.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory:
        run: |
          apt update
          apt install -y python3-wstool libgdal-dev
        shell: bash
      - name: Build Test
        working-directory:
        run: |
          mkdir -p $HOME/ros2_ws/src;
          cd $HOME/ros2_ws/src
          ln -s $GITHUB_WORKSPACE
          cd $HOME/ros2_ws
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -y
          colcon build --cmake-args --mixin release --packages-up-to grid_map_geo
        shell: bash
      # TODO add unit tests
