%YAML 1.2
---
name: Doxygen Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'ros2'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: mattnotmitt/doxygen-action@v1.9.5
